language: python

python:
- '3.8'

env:
  global:
    secure: "to6zJPXfMQ7/AHrvhNw1X0s8hrCELVp5pZ/Wnm3FmDq9m0uUySKC4rL/qv9Lo+dpeX7Ca7QyOTIaPDssLPD1MZTOA89d5CYkkuUwX/BO+y1IoCx1XbpWLoEapP8KxFYcTjol0xENVhK0E7Oy0pnpJeI9EIK/iFSmDwBjOqGbCy+s44gwx/tqIvZaNasoqzf8WmA6A7vorpwdOIvZOD6Tu6MqtseyWg3ITYA2JELx2XEOI1x+v8XOkUOLAXHZHfKKMoRZkjjSMc9U8G3E6i5+wtpCeSIKq7Ba63p6iKcHKq+/khcqozQ4EqqBDMdA177J3xg23Lr4EApcstKLykfL2nPVWqkQxvaE3hKwLqWkI9Gh0/Yho5WXNvqrFG0OtV5UJS+Jp3U0YrBGW34GIoPedJU/rxT7eyLcx47e/1BLwIN0euW8mnbOinTtPvMHHAXcEIJn8mXWbr62GwqGqqNJHbesCEY0cM+4ZP+lfKFeLT6DIqZkbFCgRj/zTV9yrUduAsJdJJtvVAfU1u7OQah/CzPCPcdksXqfNTvJiL4MM1+jQ4XXZVsNF7j4jOvdjQBKxdas/vudfXGvg7DzQT/1gWAtu/Qak/PISr72t/BkKwtM0E3oHY6ioPIVa6KZ5nzU2C0TN9wPc0Mg1vUBs7MBzDmuDZZ2dinG9A/vsCABZmE="

before_install:
- apt-get install pandoc

install:
- pip install pytest pytest-cov codecov
- python setup.py install

script:
- pytest tests

after_success:
- codecov

stages:
- test
- deploy

jobs:
  include:
    - stage: deploy
      deploy:
      - provider: pypi
        distributions: sdist
        server: https://upload.pypi.org/legacy/
        user: sorenpypi
        password:
          secure: cAbHV7rzGMwD7wAgu+WkWLV5HsA9hqTKJJFeKp16aLcGzKryhEp6SBqRw4YndcRP4OljA6R+4Yr9OyfRL0PavtQVsIE+MoEDrGJa8ZtiQ++6VVSIohLPIKsyC+tMSmDPGBOnsxHZOb6kCgWqoYMqXWCrkhaDOADR6T0ZF/9x9IQOl1b/Q23UqWMGTcFoD14WO+b4YyaDVyUCf64oC6YeBcY2ijsWW6OEiep6+JKEhZUloKvSLIiwpEPWHwSFxG3wmbh0NhAEA5ORiGmpTtUgUM4ftyBq/uEe3cRKchMVk6IXnmegdrNoa2yHsrihhmr7pAz4DM7mvCJvSV17kvxUjKbJd5rcynPOxTLOauZ3ICtcq989c5CRrj5XZ4nSGTEtmVQZLVSfrygw6OLu+ek1sgop2bbwy88CIDdsXkxN2Vm1yT1cxqzsQxmMh7pzNoqUjq358WKkT7eIO0TNh9uhjvlVhzgTUbJZrxzPpP9hm4qdtKSjxPRv7dNXEhS241vcIDjRrwVWqwG5zhmRInZwYb0UwyrmEJNNyNyt2OO1xswbVmUWxPXS88IFgHgph5UZXj5++BJ8T8IbitQN+xO633J3lUv15qfSMJ3xKVx6sJUzsFfvRATYGjW8VIU8c/vq/kt5NBeQcqhxzB3sI2v32GPD9yGPgGtsul3BKh6eNU8=
        on:
          branch: master
          tags: true
      - provider: pypi
        distributions: sdist bdist_wheel
        server: https://test.pypi.org/legacy/
        user: sorend
        password:
          secure: "JEG0A4F0oGOTCMnTPq1M58qf5VRUx5NAHcF7D+tHRsmFz2/u7/e9Juu9xv99tZUh5sTU3em4MXv+Ut5u/HKBE/EUocIUH5DaJi0AcuwRzn761Z3M3LJWXMlkGplXd51Xhj6hlokA+0MvhC9YccHT3QadhVpGyeFtVMSUV6ey7bH64OVAO09UZ69KKhjS6TVXxPVedH5+sUmlzr4y9FVAMOLQWTQr9FwNB+cCyexrIGlmodQ0WXmaMkkiFnCHHE5f07gzouHyPn4mdH7fi4D7rxj5nLlX34taioMHWjh/DmaqUNp/24u7T7IBp/tWqmdtRPtOD2MXHAbe1uI7EgmolVlrn9yxq7jy3GPJk4zXoCn69C7JiVaY9BnAIQWLVYUfUeOKTRZP4kFz58UPpZrvEucLpmGfhGYNPSv14HqV5lrlFS8l1zZ2zO+3NhWVwfgJ+n2dLLAdtUpwMOkApMPe7+vhKiUUtDCyFA59Vkjs+PIXPFmIk8wvOEPaJ8ooQclR6dtIspKWWMoGmPMM9ebhBKYOSRiBObSUST+23Xadf1h0YcLANGfDkKUrMVWHsaeotmvpyREg0+y+lrNGu4eWWeYzD7PyZ++r2FlySysm3/oMPF0AWsqTPZq7XI+j+BxpFboYGrNTgO+/VSWO8Ge9akHjF2K4zbKh0k+HrxGdxcg="
        on:
          all_branches: true
